# Generated by Django 6.0 on 2025-12-24 18:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('components', '0002_alter_cpu_options_alter_gpu_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Build',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cpu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='components.cpu')),
                ('gpu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='components.gpu')),
                ('mb', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='components.motherboard')),
                ('ram', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='components.ram')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PC Build',
                'verbose_name_plural': 'PC Builds',
            },
        ),
    ]
