# Generated by Django 6.0 on 2025-12-24 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cpu',
            options={'verbose_name': 'CPU', 'verbose_name_plural': 'CPUs'},
        ),
        migrations.AlterModelOptions(
            name='gpu',
            options={'verbose_name': 'GPU', 'verbose_name_plural': 'GPUs'},
        ),
        migrations.AlterModelOptions(
            name='motherboard',
            options={'verbose_name': 'Motherboard', 'verbose_name_plural': 'Motherboards'},
        ),
        migrations.AlterModelOptions(
            name='pricehistory',
            options={'verbose_name': 'Price History', 'verbose_name_plural': 'Price History'},
        ),
        migrations.AlterModelOptions(
            name='ram',
            options={'verbose_name': 'RAM', 'verbose_name_plural': 'RAM'},
        ),
    ]
