# Generated by Django 6.0 on 2026-01-04 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0003_alter_cpu_benchmark_score_alter_gpu_benchmark_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpu',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gpu',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ram',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
